# --- Étape 1 : build du frontend -------------------------------------------
FROM node:22-alpine AS front
WORKDIR /build
COPY frontend/package.json frontend/package-lock.json ./
RUN npm ci
COPY frontend/ ./
RUN npm run build

# --- Étape 2 : image finale - fichiers statiques uniquement ------------------
# Local-first : toute la logique (STIX, stockage IndexedDB) tourne dans le
# navigateur. Le serveur n'héberge que du code, jamais de données.
FROM nginx:alpine
COPY --from=front /build/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY nginx-security-headers.conf /etc/nginx/conf.d/dmas-security-headers.conf

# The umask of whoever cloned this repository must not decide what the server
# can serve, and until now it did. Vite copies `public/` with `copyFileSync`,
# which preserves the source mode, and `COPY --from` preserves it again: a
# clone made under a restrictive umask (root with 077, for one) puts files into
# the image that nginx cannot read. Its workers run as `nginx`, not as root, so
# the result is a 403 on the ATT&CK dataset, the country list, the logo and the
# example bundle, while the application itself loads perfectly - index.html and
# /assets/ are GENERATED by the build and get the container's umask instead.
#
# Reported from a real deployment, where it read as "403 on the example bundle"
# and looked for a while like a corporate web filter blocking a file full of
# IOCs.
#
# `a+rX`: readable by all, and traversable only where it is a directory.
RUN chmod -R a+rX /usr/share/nginx/html

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s \
    CMD ["wget", "-q", "--spider", "http://127.0.0.1/"]
