/**
 * The demo bundle served with the app (#115) must stay importable and
 * complete: it is the first thing a newcomer sees, and the one dataset
 * nobody re-reads before showing it.
 */

import "fake-indexeddb/auto";

import { afterEach, beforeEach, describe, expect, it } from "vitest";

import demoBundle from "../public/examples/operation-voliere.stix.json";
import { loadDemoInvestigation } from "./demo";
import { TOOL_IDENTITY_ID } from "./stix/bundle";
import { _resetForTests, exportBundle, importBundle, listEntities, listNotes } from "./store";

beforeEach(async () => {
  await _resetForTests();
});

describe("investigation de démonstration", () => {
  it("s'importe avec ses entités, relations et notes", async () => {
    const { investigation, report } = await importBundle(demoBundle, "Opération Volière");
    expect(report.entities).toBeGreaterThanOrEqual(20);
    expect(report.relationships).toBeGreaterThanOrEqual(25);
    // 5 analyst notes + 1 opinion
    expect(report.notes).toBe(6);

    // the bundle carries our layout extension: nothing lands in the triage tray
    const entities = await listEntities(investigation.id);
    expect(entities.every((e) => e.status === "confirmed")).toBe(true);

    // notes are attached to an entity, never orphaned
    const notes = await listNotes(investigation.id);
    expect(notes).toHaveLength(6);
    expect(notes.every((n) => n.entity_id !== null)).toBe(true);
    expect(notes.some((n) => n.kind === "opinion")).toBe(true);
  });

  it("réexporte notes et opinions, et rien d'autre (les captures restent locales)", async () => {
    const { investigation } = await importBundle(demoBundle, "Opération Volière");
    const { bundle } = await exportBundle(investigation.id, {});
    const types = bundle.objects.map((o) => o.type);
    expect(types.filter((t) => t === "note")).toHaveLength(5);
    expect(types.filter((t) => t === "opinion")).toHaveLength(1);
    // guard for #136: no binary data may leak into the STIX
    expect(JSON.stringify(bundle)).not.toMatch(/base64|image\/(png|webp)/);
  });

  it("porte exactement la tuyauterie que produit le builder", async () => {
    // The example is generated by a separate script (examples/generate-example.mjs)
    // that copies these objects by hand: without this guard it drifts on the
    // first builder change and teaches a format the tool does not actually
    // produce. It already happened once, with a private hosting URL left in
    // `schema`.
    const { investigation } = await importBundle(demoBundle, "Opération Volière");
    const { bundle } = await exportBundle(investigation.id, {});
    const tooling = (objects: { type: string; id?: string }[]) =>
      objects
        .filter((o) => o.type === "extension-definition" || o.id === TOOL_IDENTITY_ID)
        .sort((a, b) => (a.id ?? "").localeCompare(b.id ?? ""));

    expect(tooling(demoBundle.objects)).toEqual(tooling(bundle.objects));
    // and nothing of a particular host travels inside the shipped file
    expect(JSON.stringify(demoBundle)).not.toMatch(/https?:\/\/(git\.|[\d.]+:)/);
  });

  it("les entités ancrant les captures de la démo existent bien", async () => {
    const { investigation } = await importBundle(demoBundle, "Opération Volière");
    const names = new Set((await listEntities(investigation.id)).map((e) => e.name));
    // if the scenario is renamed, the demo would silently lose its attachments
    expect(names.has("nest.corax.example")).toBe(true);
    expect(names.has("http://nest.corax.example/beacon")).toBe(true);
  });
});

describe("what the demo says when the bundle does not come back", () => {
  const originalFetch = globalThis.fetch;
  afterEach(() => {
    globalThis.fetch = originalFetch;
  });

  const answer = (status: number, contentType: string, body = "{}") => {
    globalThis.fetch = (() =>
      Promise.resolve(
        new Response(body, { status, headers: { "content-type": contentType } }),
      )) as typeof fetch;
  };

  // A 403 is not a missing file. Saying "not found" for one cost a real
  // deployment an evening looking for the file instead of at its permissions.
  it("tells a refusal apart from an absence", async () => {
    answer(403, "text/html");
    await expect(loadDemoInvestigation()).rejects.toThrow(/refuses/i);
    answer(404, "text/html");
    await expect(loadDemoInvestigation()).rejects.toThrow(/missing/i);
  });

  // The SPA answers 200 with index.html on an unknown path, so a bundle left
  // out of the build reaches `json()` and dies on "Unexpected token '<'".
  it("names the real cause when the SPA answers with its own page", async () => {
    answer(200, "text/html", "<!doctype html><html></html>");
    await expect(loadDemoInvestigation()).rejects.toThrow(/not on the server/i);
  });
});
