/**
 * Non-regression for the TS port of the deterministic IDs: every vector in
 * golden-vectors.json (generated by the Python core, validated against pycti)
 * must be reproduced identically.
 */

import { describe, expect, it } from "vitest";

import golden from "./golden-vectors.json";
import {
  attackPatternId,
  campaignId,
  groupingId,
  identityId,
  indicatorId,
  infrastructureId,
  intrusionSetId,
  locationId,
  malwareId,
  noteId,
  opinionId,
  relationshipId,
  reportId,
  scoId,
  threatActorGroupId,
  threatActorIndividualId,
  toolId,
  vulnerabilityId,
} from "./ids";
import { canonicalize, type JsonValue } from "./jcs";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const DISPATCH: Record<string, (args: any) => string> = {
  attack_pattern_id: attackPatternId,
  campaign_id: campaignId,
  grouping_id: groupingId,
  identity_id: identityId,
  indicator_id: indicatorId,
  infrastructure_id: infrastructureId,
  intrusion_set_id: intrusionSetId,
  location_id: locationId,
  malware_id: malwareId,
  note_id: noteId,
  opinion_id: opinionId,
  relationship_id: relationshipId,
  report_id: reportId,
  threat_actor_group_id: threatActorGroupId,
  threat_actor_individual_id: threatActorIndividualId,
  tool_id: toolId,
  vulnerability_id: vulnerabilityId,
};

describe("vecteurs golden - SDO (recettes OpenCTI/pycti)", () => {
  for (const c of golden.cases) {
    it(`${c.fn} ${JSON.stringify(c.args)}`, () => {
      const fn = DISPATCH[c.fn];
      expect(fn, `fonction non portée : ${c.fn}`).toBeDefined();
      expect(fn(c.args)).toBe(c.expected);
    });
  }
});

describe("vecteurs golden - SCO (spec STIX 2.1)", () => {
  for (const c of golden.sco_cases) {
    it(`${c.type} ${JSON.stringify(c.props)}`, () => {
      expect(scoId(c.type, c.props as unknown as Record<string, JsonValue>)).toBe(c.expected);
    });
  }
});

describe("invariants", () => {
  it("valeur golden historique : intrusion-set APT28", () => {
    expect(intrusionSetId({ name: "APT28" })).toBe(
      "intrusion-set--f743ab1d-b2f2-58f8-975f-0993511c0b9d",
    );
  });

  it("relationship : stop_time sans start_time est ignoré", () => {
    const base = {
      relationship_type: "uses",
      source_ref: "threat-actor--0225e0e0-3a4d-5f5f-8b3f-6b6f5c8d9e0a",
      target_ref: "malware--1336f1f1-4b5e-6a6a-9c4a-7c7a6d9e0f1b",
    };
    expect(relationshipId({ ...base, stop_time: "2026-02-01T00:00:00.000Z" })).toBe(
      relationshipId(base),
    );
  });

  it("JCS : tri des clés et échappement conformes RFC 8785", () => {
    expect(canonicalize({ b: 1, a: "é\n", Z: [true, null] })).toBe(
      '{"Z":[true,null],"a":"é\\n","b":1}',
    );
  });

  it("file : préférence MD5 quand plusieurs hashes", () => {
    const md5Only = scoId("file", {
      hashes: { MD5: "44d88612fea8a8f36de82e1278abb02f" },
    });
    const both = scoId("file", {
      name: "dropper.dll",
      hashes: {
        MD5: "44d88612fea8a8f36de82e1278abb02f",
        "SHA-256": "aec070645fe53ee3b3763059376134f058cc337247c978add178b6ccdfb0019f",
      },
    });
    // the name contributes too: the two IDs differ, but the hash kept is MD5
    expect(both).not.toBe(md5Only);
  });
});
